### ISSUE TITLE
Tag counters are not updating

### ISSUE THREAD

**Issue by mistadikay** [astralapp/astral#116]
Hey! Awesome app, love it and use it.

A small, but annoying bug: after unstaring a bunch of repos I noticed that though they successfully disappeared from Astral after syncing, the number of the tag contained them stayed the same. For example, there is only one repo left under `analysis` tag, but it still shows the old number.
![screenshot 2016-11-27 02 09 49](https://cloud.githubusercontent.com/assets/742056/20644848/addca1f0-b446-11e6-83a1-7972031d5dd8.png)

**Comment by syropian** [comment]
This is actually an interesting problem that I never thought about before. Behind the scenes we create a new record whenever you tag a repository but we dont consistently cross-check those records with the current star list in case a repo has been unstarred. Since those checks never happen, certain records never get deleted from the DB.

I'll have to include a "cleanup" phase after fetching all stars that does this cross-check and removes any records for stars that no longer exist. 

Thanks for reporting this!

**Comment by syropian** [comment]
Hey @mistadikay! This was fixed in #142, let me know how it works for you. Cheers!
