### ISSUE TITLE
intuitive tag editing

### ISSUE THREAD

**Issue by muescha** [astralapp/astral#120]
- the tag editbox from [2] should appear when i click on point near the tag list at [1]
- the tag delete icon should appear at the tag row at [1] when i hoover over a tag
<img width="693" alt="ScreenShot" src="https://cloud.githubusercontent.com/assets/184316/21032351/46be8be8-bda9-11e6-954e-30191132ff01.png">

**Comment by syropian** [comment]
Thanks for the feedback. I have a few ideas bouncing around about tag editing, I'll take this into consideration 👍

**Comment by riccardoferretti** [comment]
If it can be helpful, a couple of things around tag editing I noticed: 

- would be great if cmd+enter would save the tags
- would be great to have inline tag editing (that is, just editing in [1] instead of having to click the "Edit Tags" option)

I feel the combination of the two would make bulk tagging (which I found being my personal most used way of using Astral) much faster.
(btw, amazing work!)
